num1 = input('Enter first number: ')     
num2 = input('Enter second number: ')        
sum = float(num1) + float(num2)      
print(sum)
min = float(num1) - float(num2)
print(min)
Mul = float(num1) * float(num2)
print(Mul)
div = float(num1) - float(num2)
print(div)
